/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "iazguenkfutcyzenxmdn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhemd1ZW5rZnV0Y3l6ZW54bWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzQyNzcsImV4cCI6MjA3NDMxMDI3N30.81BdA9_nZ_JUNRcrIjSc61pP276w-8PBatjzWy1ID-M"